### ISSUE TITLE
Network error while trying to login

### ISSUE THREAD

**Issue by speedymlg** [Avenshy/MajsoulMax#10]
![image](https://github.com/Avenshy/MajsoulMax/assets/20207183/1f0e275a-a6f8-443d-bdb5-f4a1a95430c3)
With proxifier setup and majsoulmax application running

**Comment by Avenshy** [comment]
请截图控制台的报错。

---

Machine translation: 

please take a screenshot of the console reporting the error.

**Comment by speedymlg** [comment]
![image](https://github.com/Avenshy/MajsoulMax/assets/20207183/03172e3b-689d-4af7-b5e8-31e43ebb617e)
![image](https://github.com/Avenshy/MajsoulMax/assets/20207183/0650378c-b00b-46db-9109-cea34fcf159c)

Here they are

**Comment by Avenshy** [comment]
应该是没有安装证书引起的，可以尝试以下方法安装证书：
1. 运行MajsoulMax
2. 关闭所有浏览器窗口
3. 将Chrome或者Edge的快捷方式 `复制->粘贴` 出现一个副本，对快捷方式副本 `右键->属性->目标` 的后面按一个空格后添加` --proxy-server=127.0.0.1:23410 ` 
4. 运行这个快捷方式，访问`mitm.it` 
5. 下载并安装证书
6. 正常启动游戏，再次尝试

或google搜索：mitmproxy 安装证书

---
Machine translation:

It should be caused by not installing the certificate, you can try the following methods:
1. Run MajsoulMax
2. Close all browser windows
3. `Copy->Paste` a copy of the Chrome or Edge shortcut, `Right-click->Properties->Target` the copy of the shortcut and add ` --proxy-server=127.0.0.1:23410` after pressing a space. 
4. Run the shortcut and go to `mitm.it`. 
5. Download and install the certificate
6. Start the game normally and try again

Or google search: `mitmproxy install certificate`

**Comment by speedymlg** [comment]
i am on `mitm.it` and this is what shows up
![image](https://github.com/Avenshy/MajsoulMax/assets/20207183/907c7c01-faf0-4ac4-a940-b316baa69e44)

**Comment by speedymlg** [comment]
I have figured out on how to install mitproxy, and majsoulmax now works as intended and I no longer need assistance, thank you.

**Comment by SchezoWegey** [comment]
> I have figured out on how to install mitproxy, and majsoulmax now works as intended and I no longer need assistance, thank you.

Hey I am having the same issue you did prior. I also installed mitproxy and I know how to launch it, however from there I am stumped on what to do. Going to mitm.it just gives me a cirtificate installer but with no cirtificate to install.

Could you tell me what you did to get the cirtificates installed? Thank you.
